# Generated by Django 2.1.5 on 2019-01-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190124_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='', max_length=50, verbose_name='用户名'),
        ),
    ]
